### PR TITLE
Code cleanup and PSR-2 compatibility

### PR DESCRIPTION
**Pull request by RSpeekenbrink**
Cleanup the code to comply with the more modern best practices.

And a small request to add a 0.3.0 tag or release 1.0.0 since its bad to use an adoption of the master branch 😅

### CODE REVIEW

**Comment by barryvdh** [comment]
This doesn't change functionality right3? So why is a tag needed?

**Comment by RSpeekenbrink** [comment]
No it doesn't change functionality but the readme sugests installing v0.3.0. This tag does not exist yet and thereby it installs dev-master since the branch is defined as 0.3-dev in the composer json. If there are changes in functionality to be made in the master branch this can cause conflicts on production environments using the suggested 0.3.* version.

**Comment by RSpeekenbrink** [comment]
I just saw that the latest functionality changes are tagged as 0.2.1. Maybe make that the suggested version in the readme or remove versioning from the require command in the readme in total?

**Comment by barryvdh** [comment]
Yeah we should just remove the version there

**Pull request merged**
